### ISSUE TITLE
I cant run this and where is the server code please

### ISSUE THREAD

**Issue by ghost** [baconcheese113/chat2getherRN#1]

**Comment by baconcheese113** [comment]
Server code is included, you probably won't be able to run it without a ton of environment configuration. I'd use it more for reading through the code to understand use-cases for different apis

**Comment by ghost** [comment]
Ok thank you very, I am waiting for your efforts

**Comment by baconcheese113** [comment]
Are you trying to understand how to use react-native-webrtc?

**Comment by ghost** [comment]
Yeah I trying to using webrtc

**Comment by baconcheese113** [comment]
On the client, I perform the handshake through socket.io with my own helper class https://github.com/baconcheese113/chat2getherRN/blob/master/src/helpers/socketHelper.js

The signaling server code is here
https://github.com/baconcheese113/chat2gether/blob/master/server/src/socket.js

**Comment by ghost** [comment]
Thank you this errors generate

Failed to install the app. Make sure you have the Android development environment set up

**Comment by baconcheese113** [comment]
I would recommend doing 5-10 basic RN apps before trying a fullstack webrtc app with server code

**Comment by ghost** [comment]
Please add some guide line on the repo
